name: .NET formatting

on:
  push:
    branches: [ "master" ]
  pull_request:

concurrency: 
  group: ci-format-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 6.0.x

    - name: Format
      continue-on-error: true
      run: dotnet format

    - name: Commit changes
      continue-on-error: true
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name format-bot
        git config user.email bot@DaanV2.com
        git add .
        git commit -m "auto: Generated markdown indexes pages"
        git push
        
